from itertools import combinations

samples = ['3MG3L',
           '3MG3M',
           '3MG3N',
           '3MG3O',
           '3MG3P',
           '3MG3R',
           '3MG3U',
           '3MG3V',
           '3MG3Y',
           '3MG3Z',
           '3MG45',
           '3MG46',
           '3MG47',
           '3MG48',
           '3MG49',
           '3MG4A',
           '3MG4B',
           '3MG4C',
           '3MG4D',
           '3MG4E',
           '3MG4F',
           '3MG4G',
           '3MG4H',
           '3MG4J',
           '3MG4K',
           '3MG4L',
           '3MG4M',
           '3MG4N',
           '3MG4O',
           '3MG4P',
           '3MG4Q',
           '3MG4R',
           '3MG4S',
           '3MG4T',
           '3MG4U',
           '3MG4V',
           '3MG4W',
           '3MG4X',
           '3MG4Y',
           '3MG51',
           '3MG52',
           '3MG53',
           '3MG54',
           '3MG55',
           '3MG56',
           '3MG57',
           '3MG58',
           '3MG59',
           '3MG5A',
           '3MG5B',
           '3MG5C',
           '3MG5D',
           '3MG5E',
           '3MG5F',
           '3MG5G',
           '3MG5H',
           '3MG5J',
           '3MG5L',
           '3MG5M',
           '3MG5N',
           '3MG5O',
           '3MG5P',
           '3MG5Q',
           '3MG5R',
           '3MG5S',
           '3MG5T',
           '3MG5U',
           '3MG5V',
           '3MG5W',
           '3MG5Y',
           '3MG5Z',
           '3MG61',
           '3MG62',
           '3MG63',
           '3MG64',
           '3MG65',
           '3MG66',
           '3MG67',
           '3MG68',
           '3MG69',
           '3MG6A',
           '3MG6B',
           '3MGPL',
           '3MGPN',
           '3MGPO',
           '3MGPP',
           '3MGPQ',
           '3MGPR',
           '3MGPS',
           '3MGPU',
           '3MGPV',
           '3MGPW',
           '3MGPX',
           '3MGPY',
           '3MGPZ',]

plantilla = """
#BSUB -q medium
#BSUB -J {job}
#BSUB -o /home/inmegen/r.garcia/100g/intersects/{job}


/home/inmegen/r.garcia/local/bin/python /home/inmegen/r.garcia/100g/scripts/intersect_size.py /home/inmegen/r.garcia/100g/beds/{S1}.bed_set.pickle /home/inmegen/r.garcia/100g/beds/{S2}.bed_set.pickle
"""

for pair in combinations(samples, 2):
    job = "%s_%s" % pair
    with open('%s.job' % job, 'w') as script:
        script.write(plantilla.format(job=job, S1=pair[0], S2=pair[1]))
